version: 2.1

workflows:
  igvf-catalog-tests:
    jobs:
      - lint
      - data:
          requires:
            - lint
      - build:
          requires:
            - lint
      - trpc:
          requires:
            - lint

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/igvf-catalog
    steps:
      - checkout
      - run: pip install pre-commit==3.2.1
      - run: pre-commit run --all-files
  trpc:
    docker:
      - image: cimg/node:18.14.0
    resource_class: large
    working_directory: ~/igvf-catalog
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Jest tests
          command: npm test --maxWorkers=2 --logHeapUsage --detectOpenHandles
      - run:
          name: Upload coverage report
          command: cat coverage/lcov.info | npx coveralls --verbose
  data:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/igvf-catalog/data
    steps:
      - checkout:
          path: ~/igvf-catalog
      - run:
          name: Install dependencies
          command: |
            pip3 install -r requirements.txt
            pip install coverage-lcov coveralls
      - run:
          name: Run tests with coverage
          command: pytest --cov=adapters --cov=db --cov-report=term-missing --cov-report=html --cov-report=xml
      - run:
          name: Upload coverage report
          command: coveralls
          when: always
  build:
    docker:
      - image: cimg/node:20.11
    resource_class: medium
    working_directory: ~/igvf-catalog
    steps:
      - checkout
      - run: npm install
      - run: npm run build
