version: 2.1

workflows:
  igvf-catalog-tests:
    jobs:
      - trpc
      - data

jobs:
  trpc:
    docker:
      - image: cimg/node:18.14.0
    working_directory: ~/igvf-catalog
    steps:
      - checkout
      - run: npm install
      - run: npm test
  data:
    working_directory: ~/igvf-catalog/data
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: pytest
          