version: 2.1

workflows:
  igvf-catalog-tests:
    jobs:
      - lint
      - trpc:
          requires:
            - lint
      - data:
          requires:
            - lint
      - build:
          requires:
            - lint

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/igvf-catalog
    steps:
      - checkout
      - run: pip install pre-commit==3.2.1
      - run: pre-commit run --all-files
  trpc:
    docker:
      - image: cimg/node:18.14.0
    working_directory: ~/igvf-catalog
    steps:
      - checkout
      - run: npm install
      - run: npm test
  data:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/igvf-catalog/data
    steps:
      - checkout:
          path: ~/igvf-catalog
      - run: pip3 install -r requirements.txt
      - run: pytest
  build:
    docker:
      - image: cimg/node:18.14.0
    working_directory: ~/igvf-catalog
    steps:
      - checkout
      - run: npm install
      - run: npm run build
