import os
import pickle
import json

S3 = 's3://igvf-catalog-parsed-collections/variants/'
FAVOR = 'favor_chrC_spdi_key_format.jsonl'
TOPLDs = ['topld_eur_chrC_key.jsonl', 'topld_eas_chrC_key.jsonl',
          'topld_afr_chrC_key.jsonl', 'topld_sas_chrC_key.jsonl']


def load_favor(chr):
    favor = FAVOR.replace('C', str(chr))
    pickle_path = 'favor_chr' + str(chr) + '_keys.pickle'

    if os.path.exists(pickle_path):
        with open(pickle_path, 'rb') as inputt:
            return set(pickle.load(inputt))

    if not os.path.exists(favor):
        os.system('aws s3 cp ' + S3 + favor + ' .')

    ids = []
    for line in open(favor, 'r'):
        data = json.loads(line)
        ids.append(data['_key'])

    with open(pickle_path, 'wb') as output:
        pickle.dump(ids, output)

    os.remove(favor)

    return set(ids)


def create_variant(data):
    variant_data = data.split(':')
    return {
        'chr': variant_data[0],
        'pos': int(variant_data[1]),
        'ref': variant_data[2],
        'alt': variant_data[3],
        'source': 'Autogenerated from TopLD',
        'source_url': 'http://topld.genetics.unc.edu/'
    }


def process_chr(chr):
    favor_keys = load_favor(chr)

    output = open('chrC.jsonl'.replace('C', chr), 'w+')

    for topld in TOPLDs:
        topld_path = topld.replace('C', str(chr))

        if not os.path.exists(topld_path):
            os.system('aws s3 cp ' + S3.replace('variants/',
                      'variants_variants/') + topld_path + ' .')

        for line in open(topld_path, 'r'):
            data = json.loads(line)

            if data['_from'].split('variants/')[1] not in favor_keys:
                if data['variant_1_rsid'].startswith('chr'):
                    variant = create_variant(data['variant_1_rsid'])
                    output.write(json.dumps(variant) + '\n')

            if data['_to'].split('variants/')[1] not in favor_keys:
                if data['variant_2_rsid'].startswith('chr'):
                    variant = data['variant_2_rsid'].split(':')
                    output.write(json.dumps(variant) + '\n')

        os.remove(topld_path)

    output.close()


[process_chr(c) for c in range(1, 23) + ['X']]
