from adapters.helpers import build_spdi, build_hgvs_from_spdi
import os
import json
from pathlib import Path

from arango import ArangoClient
from jsonschema import ValidationError, validate

from ga4gh.vrs.extras.translator import AlleleTranslator
from ga4gh.vrs.dataproxy import create_dataproxy
from biocommons.seqrepo import SeqRepo
import sys
sys.path.append(os.path.abspath(
    os.path.join(os.path.dirname(__file__), '..')))

OUTPUT_PATH = 'autogenerated_dbnsfp_variants.jsonl'
SCHEMA_PATH = 'data/schemas/nodes/variants.autogenerated_dbnsfp.json'
DB_NAME = 'igvf'
ARANGODB_URL = 'http://localhost:8529'
USERNAME = 'username'
PASSWORD = 'password'
BATCH_SIZE = 10000

client = ArangoClient()
db = client.db(DB_NAME, username=USERNAME, password=PASSWORD)

dp = create_dataproxy(
    'seqrepo+file:///usr/local/share/seqrepo/2024-12-20')
seq_repo = SeqRepo('/usr/local/share/seqrepo/2024-12-20')
translator = AlleleTranslator(data_proxy=dp)

with open(SCHEMA_PATH) as f:
    schema = json.load(f)


def build_variant_doc(variant_key: str, edge: dict) -> dict:
    chr = edge.get('chr', '')
    pos = edge.get('pos')
    ref = edge.get('ref', '')
    alt = edge.get('alt', '')

    spdi = build_spdi(chr, pos, ref, alt, translator, seq_repo)
    hgvs = build_hgvs_from_spdi(spdi)

    return {
        '_key': variant_key,
        'name': spdi,
        'chr': chr,
        'pos': pos,
        'ref': ref,
        'alt': alt,
        'spdi': spdi,
        'hgvs': hgvs,
        'organism': 'Homo sapiens',
        'variation_type': 'SNP',
        'source': 'Autogenerated from dbNSFP 5.1a',
        'source_url': 'https://www.dbnsfp.org/'
    }


edges_col = db.collection('variants_coding_variants')
total_edges = edges_col.count()

total_written = total_invalid = 0
offset = 0

with open(OUTPUT_PATH, 'w') as out_file:
    while offset < total_edges:
        print('Processing edges %d – %d ...' %
              (offset, min(offset + BATCH_SIZE, total_edges)))

        batch = list(db.aql.execute(
            """
            FOR edge IN variants_coding_variants
              LIMIT @offset, @batch
              LET exists = DOCUMENT(edge._from)
              FILTER exists == null
              RETURN {
                _from:  edge._from,
                chr:    edge.chr,
                pos:    edge.pos,
                ref:    edge.ref,
                alt:    edge.alt,
                source: edge.source
              }
            """,
            bind_vars={'offset': offset, 'batch': BATCH_SIZE},
        ))

        if not batch:
            offset += BATCH_SIZE
            continue

        seen: set[str] = set()
        for edge in batch:
            variant_id = edge['_from']
            if not variant_id.startswith('variants/') or variant_id in seen:
                continue
            seen.add(variant_id)

            variant_key = variant_id.split('/', 1)[1]
            doc = build_variant_doc(variant_key, edge)

            try:
                validate(instance=doc, schema=schema)
            except ValidationError as exc:
                print('Schema validation failed for %s: %s' %
                      (variant_key, exc.message))
                total_invalid += 1
                continue

            out_file.write(json.dumps(doc) + '\n')
            total_written += 1

        print('  → written so far: %d | invalid so far: %d' %
              (total_written, total_invalid))
        offset += BATCH_SIZE

    print('Done. Written: %d | Skipped (invalid): %d → %s' %
          (total_written, total_invalid, OUTPUT_PATH))
