import { Router, type Request, type Response } from 'express'
import { CloudWatchLogsClient, DescribeLogGroupsCommand, GetQueryResultsCommand, StartQueryCommand } from '@aws-sdk/client-cloudwatch-logs'
import { db } from '../database'

// This is a LOCAL-ONLY tool (see src/internal/analyticsServer.ts) - it is
// never deployed, so there's no task role to grant IAM permissions to and
// no reason to gate it behind a token: it binds to localhost only, and
// whoever runs it uses their own AWS SSO session (needs read/query access
// to CloudWatch Logs for the account it's pointed at) and DB credentials
// (via IGVF_CATALOG_ARANGODB_* env vars, or the config/development.json
// defaults for zero setup against the dev DB).

const POLL_INTERVAL_MS = 1000
const MAX_POLL_ATTEMPTS = 30
const DEFAULT_HOURS = 24
// Every account/region this app deploys to (dev, demo, production - see
// cdk_swagger/infrastructure/constructs/existing/{catalog_dev,catalog_prod}.py)
// is us-west-2; unlikely to change, so this is hardcoded rather than read
// from an AWS_REGION env var.
const AWS_REGION = 'us-west-2'

type Stage = 'dev' | 'production'

// This app's own nginx access-log group, found purely by pattern search.
// These substrings come from naming in cdk_swagger/infrastructure/naming.py
// and stages/{dev,production}.py: 'igvf-catalog-api-<branch>-<Stage>Deploy
// Stage-FrontendStack-...nginxLogGroup...', where <branch> is 'dev' for the
// dev pipeline and 'main' for the production pipeline (the branch that
// triggers each self-updating CodePipeline). The trailing ID is CDK/
// CloudFormation-autogenerated and can change across deploys, which is why
// this resolves it live via DescribeLogGroups rather than a fixed full name.
const LOG_GROUP_NAME_PATTERNS: Record<Stage, string> = {
  dev: 'igvf-catalog-api-dev-DevelopmentDeployStage-FrontendStack-FrontendFargateTaskDefnginxLogGroup',
  production: 'igvf-catalog-api-main-ProductionDeployStage-FrontendStack-FrontendFargateTaskDefnginxLogGroup'
}

// Picked in the panel UI, since a local AWS session may only have access to
// one of the two accounts (or both) - picking the wrong one just fails
// cleanly (no access to that account's log group) rather than returning
// another account's data.
function resolveStage (req: Request): Stage {
  return req.query.stage === 'production' ? 'production' : 'dev'
}

const cloudWatchLogsClient = new CloudWatchLogsClient({ region: AWS_REGION })

// Keyed by stage, since a single running process can be asked to resolve
// either stage (the panel lets a human pick per request) - caching one
// shared value here would leak whichever stage was resolved first into
// every later request regardless of what it actually asked for.
const nginxLogGroupNameCache = new Map<Stage, string>()

async function resolveNginxLogGroupName (stage: Stage): Promise<string> {
  const cached = nginxLogGroupNameCache.get(stage)
  if (cached !== undefined) {
    return cached
  }

  const pattern = LOG_GROUP_NAME_PATTERNS[stage]
  const candidates: Array<{ name: string, creationTime: number }> = []
  let nextToken: string | undefined

  do {
    const response = await cloudWatchLogsClient.send(new DescribeLogGroupsCommand({
      logGroupNamePattern: pattern,
      nextToken
    }))
    for (const group of response.logGroups ?? []) {
      if (group.logGroupName !== undefined) {
        candidates.push({ name: group.logGroupName, creationTime: group.creationTime ?? 0 })
      }
    }
    nextToken = response.nextToken
  } while (nextToken !== undefined)

  if (candidates.length === 0) {
    throw new Error(`No CloudWatch log group matched pattern "${pattern}"`)
  }

  // If a past deploy replaced the (CDK-autogenerated) log group, there may
  // be a stale leftover alongside the current one - the most recently
  // created match is the active one.
  candidates.sort((a, b) => b.creationTime - a.creationTime)
  const resolvedName = candidates[0].name
  nginxLogGroupNameCache.set(stage, resolvedName)
  return resolvedName
}

// Strips the query string (nginx logs it in full, so it isn't safe to group by)
// and pulls out the field nginx's custom log_format adds (docker/nginx/production.conf).
const TOP_PATHS_QUERY = `
parse @message /"(?<verb>\\S+) (?<urlpath>[^\\s?"]+)\\S* HTTP/
| parse @message /request_time=(?<request_time>[\\d.]+)/
| stats count(*) as hits, avg(request_time) as avg_s, min(request_time) as min_s, max(request_time) as max_s, pct(request_time, 95) as p95_s by urlpath
| sort hits desc
| limit 50
`

// Same idea, but keeps the query string too, to see which specific calls
// (not just which endpoint) are actually popular, and which one hit each
// path's min/max response time. Grouped globally rather than per-path,
// since Logs Insights has no "top N per group" - MAX_CALLS_ROWS is enough
// to cover the popular paths' popular calls, but a path whose traffic is
// mostly long-tail (each distinct call happening once) may come up short:
// its min/max example and popular-calls breakdown could point at whichever
// calls happened to make the cut, not the true extremes across every call
// ever made to it in the window (min_s/max_s on TOP_PATHS_QUERY above are
// still exact, since those aggregate over the complete, ungrouped dataset).
const MAX_CALLS_ROWS = 5000
const TOP_CALLS_PER_PATH = 8
const TOP_CALLS_QUERY = `
parse @message /"(?<verb>\\S+) (?<urlpath>[^\\s?"]+)(\\?(?<querystring>[^\\s"]*))? HTTP/
| parse @message /request_time=(?<request_time>[\\d.]+)/
| stats count(*) as hits, avg(request_time) as avg_s, min(request_time) as min_s, max(request_time) as max_s by urlpath, querystring
| sort hits desc
| limit ${MAX_CALLS_ROWS}
`

interface TopCall {
  querystring: string
  hits: number
  avgSeconds: number
}

interface TopPath {
  urlpath: string
  hits: number
  avgSeconds: number
  minSeconds: number
  maxSeconds: number
  p95Seconds: number
  minExampleQuerystring: string | undefined
  maxExampleQuerystring: string | undefined
  topCalls: TopCall[]
}

type SlowQuery = Awaited<ReturnType<typeof db.listSlowQueries>>[number]

interface DbHealthSnapshot {
  slowQueries: SlowQuery[]
  queueTimeAvg: number
  queueTimeLatest: number | undefined
}

async function sleep (ms: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms))
}

async function runInsightsQuery (logGroupName: string, startTime: number, endTime: number, queryString: string): Promise<Array<Record<string, string>>> {
  const startResponse = await cloudWatchLogsClient.send(new StartQueryCommand({
    logGroupName,
    startTime,
    endTime,
    queryString
  }))

  if (startResponse.queryId === undefined) {
    throw new Error('CloudWatch Logs Insights did not return a queryId')
  }

  for (let attempt = 0; attempt < MAX_POLL_ATTEMPTS; attempt++) {
    const results = await cloudWatchLogsClient.send(new GetQueryResultsCommand({ queryId: startResponse.queryId }))

    if (results.status === 'Complete') {
      return (results.results ?? []).map((row) => {
        const fields: Record<string, string> = {}
        for (const field of row) {
          if (field.field !== undefined && field.value !== undefined) {
            fields[field.field] = field.value
          }
        }
        return fields
      })
    }

    if (results.status === 'Failed' || results.status === 'Cancelled' || results.status === 'Timeout') {
      throw new Error(`CloudWatch Logs Insights query ended with status ${String(results.status)}`)
    }

    await sleep(POLL_INTERVAL_MS)
  }

  throw new Error('CloudWatch Logs Insights query timed out waiting for results')
}

function decodeQuerystring (querystring: string): string {
  try {
    return decodeURIComponent(querystring)
  } catch {
    return querystring
  }
}

interface PathExtremes {
  minSeconds: number
  minQuerystring: string
  maxSeconds: number
  maxQuerystring: string
}

async function queryCallBreakdownByPath (logGroupName: string, startTime: number, endTime: number): Promise<{
  topCallsByPath: Map<string, TopCall[]>
  extremesByPath: Map<string, PathExtremes>
}> {
  const rows = await runInsightsQuery(logGroupName, startTime, endTime, TOP_CALLS_QUERY)

  const topCallsByPath = new Map<string, TopCall[]>()
  const extremesByPath = new Map<string, PathExtremes>()

  for (const fields of rows) {
    if (fields.querystring === undefined) {
      continue
    }
    const urlpath = fields.urlpath ?? '(unmatched)'
    const querystring = decodeQuerystring(fields.querystring)
    const hits = Number(fields.hits ?? '0')
    const avgSeconds = Number(fields.avg_s ?? '0')
    const minSeconds = Number(fields.min_s ?? '0')
    const maxSeconds = Number(fields.max_s ?? '0')

    const topCalls = topCallsByPath.get(urlpath) ?? []
    if (topCalls.length < TOP_CALLS_PER_PATH) {
      topCalls.push({ querystring, hits, avgSeconds })
      topCallsByPath.set(urlpath, topCalls)
    }

    const extremes = extremesByPath.get(urlpath)
    if (extremes === undefined) {
      extremesByPath.set(urlpath, { minSeconds, minQuerystring: querystring, maxSeconds, maxQuerystring: querystring })
    } else {
      if (minSeconds < extremes.minSeconds) {
        extremes.minSeconds = minSeconds
        extremes.minQuerystring = querystring
      }
      if (maxSeconds > extremes.maxSeconds) {
        extremes.maxSeconds = maxSeconds
        extremes.maxQuerystring = querystring
      }
    }
  }

  return { topCallsByPath, extremesByPath }
}

async function queryTopPaths (logGroupName: string, startTime: number, endTime: number): Promise<TopPath[]> {
  const [pathRows, { topCallsByPath, extremesByPath }] = await Promise.all([
    runInsightsQuery(logGroupName, startTime, endTime, TOP_PATHS_QUERY),
    queryCallBreakdownByPath(logGroupName, startTime, endTime)
  ])

  return pathRows.map((fields) => {
    const urlpath = fields.urlpath ?? '(unmatched)'
    const extremes = extremesByPath.get(urlpath)
    return {
      urlpath,
      hits: Number(fields.hits ?? '0'),
      avgSeconds: Number(fields.avg_s ?? '0'),
      minSeconds: Number(fields.min_s ?? '0'),
      maxSeconds: Number(fields.max_s ?? '0'),
      p95Seconds: Number(fields.p95_s ?? '0'),
      minExampleQuerystring: extremes?.minQuerystring,
      maxExampleQuerystring: extremes?.maxQuerystring,
      topCalls: topCallsByPath.get(urlpath) ?? []
    }
  })
}

async function getDbHealthSnapshot (): Promise<DbHealthSnapshot> {
  const slowQueries = await db.listSlowQueries()
  slowQueries.sort((a, b) => b.runTime - a.runTime)
  return {
    slowQueries,
    queueTimeAvg: db.queueTime.getAvg(),
    queueTimeLatest: db.queueTime.getLatest()
  }
}

function parseHours (rawHours: unknown): number {
  const hours = Number(rawHours)
  return Number.isFinite(hours) && hours > 0 ? hours : DEFAULT_HOURS
}

async function handleQueriesRequest (req: Request, res: Response): Promise<void> {
  const stage = resolveStage(req)
  const hours = parseHours(req.query.hours)
  const endTime = Math.floor(Date.now() / 1000)
  const startTime = endTime - Math.floor(hours * 3600)

  const nginxLogGroupName = await resolveNginxLogGroupName(stage)

  const [topPaths, dbHealth] = await Promise.all([
    queryTopPaths(nginxLogGroupName, startTime, endTime),
    getDbHealthSnapshot()
  ])

  res.json({ hours, topPaths, dbHealth })
}

const PANEL_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Catalog API analytics</title>
<style>
  body { font-family: -apple-system, sans-serif; margin: 2rem; }
  table { border-collapse: collapse; width: 100%; margin-top: 1rem; }
  th, td { border: 1px solid #ccc; padding: 0.4rem 0.6rem; text-align: left; font-size: 0.9rem; vertical-align: top; }
  th { background: #f4f4f4; }
  details { max-width: 32rem; }
  details summary { cursor: pointer; font-family: monospace; font-size: 0.85rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  details pre { white-space: pre-wrap; word-break: break-all; max-height: 220px; overflow: auto; background: #f8f8f8; padding: 0.5rem; margin-top: 0.3rem; }
  #status.error { color: #a00; }
</style>
</head>
<body>
<h1>Catalog API analytics</h1>
<p>
  Stage: <select id="stage"><option value="dev">dev</option><option value="production">production</option></select>
  Hours: <input type="number" id="hours" value="24" style="width: 4rem">
  <button id="load">Load</button>
</p>
<p id="status"></p>
<h2>Top paths</h2>
<table id="topPaths">
  <thead><tr><th>Path</th><th>Hits</th><th>Avg (s)</th><th>Min (s)</th><th>Max (s)</th><th>p95 (s)</th><th>Popular calls</th></tr></thead>
  <tbody></tbody>
</table>
<h2>DB health during this window</h2>
<p>Queue time (ArangoDB backlog signal) - latest: <span id="queueLatest"></span>s, avg: <span id="queueAvg"></span>s</p>
<table id="slowQueries">
  <thead><tr><th>Started</th><th>Run time (s)</th><th>State</th><th>Query</th><th>Bind vars</th></tr></thead>
  <tbody></tbody>
</table>
<script>
function esc (value) {
  return String(value).replace(/[&<>"']/g, function (ch) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]
  })
}

function truncateOneLine (text, maxLen) {
  const oneLine = text.replace(/\\s+/g, ' ').trim()
  return oneLine.length > maxLen ? oneLine.slice(0, maxLen) + '...' : oneLine
}

// summaryLabel stays visible; clicking reveals fullText in a selectable,
// copyable <pre> - used both for truncated long text (query/bind vars) and
// for a short label that expands into unrelated full text (min/max cells).
function makeCollapsible (fullText, summaryLabel) {
  const details = document.createElement('details')
  const summary = document.createElement('summary')
  summary.textContent = summaryLabel
  const pre = document.createElement('pre')
  pre.textContent = fullText
  details.appendChild(summary)
  details.appendChild(pre)
  return details
}

function renderTopPaths (topPaths) {
  const tbody = document.querySelector('#topPaths tbody')
  tbody.innerHTML = ''
  for (const row of topPaths) {
    const tr = document.createElement('tr')
    tr.innerHTML = '<td>' + esc(row.urlpath) + '</td><td>' + row.hits + '</td><td>' +
      row.avgSeconds.toFixed(3) + '</td>'

    const minCell = document.createElement('td')
    const minEndpoint = row.urlpath + (row.minExampleQuerystring ? '?' + row.minExampleQuerystring : '')
    minCell.appendChild(makeCollapsible(minEndpoint, row.minSeconds.toFixed(3)))
    tr.appendChild(minCell)

    const maxCell = document.createElement('td')
    const maxEndpoint = row.urlpath + (row.maxExampleQuerystring ? '?' + row.maxExampleQuerystring : '')
    maxCell.appendChild(makeCollapsible(maxEndpoint, row.maxSeconds.toFixed(3)))
    tr.appendChild(maxCell)

    const p95Cell = document.createElement('td')
    p95Cell.textContent = row.p95Seconds.toFixed(3)
    tr.appendChild(p95Cell)

    const callsCell = document.createElement('td')
    if (row.topCalls.length > 0) {
      const summaryLabel = row.topCalls.length + ' repeated call(s)'
      const fullText = row.topCalls.map(function (call) {
        return '(' + call.hits + 'x, avg ' + call.avgSeconds.toFixed(3) + 's) ?' + call.querystring
      }).join('\\n')
      callsCell.appendChild(makeCollapsible(fullText, summaryLabel))
    } else {
      callsCell.textContent = 'no repeated calls in this window'
    }
    tr.appendChild(callsCell)
    tbody.appendChild(tr)
  }
}

function renderDbHealth (dbHealth) {
  document.getElementById('queueLatest').textContent = String(dbHealth.queueTimeLatest ?? 'n/a')
  document.getElementById('queueAvg').textContent = dbHealth.queueTimeAvg.toFixed(3)

  const tbody = document.querySelector('#slowQueries tbody')
  tbody.innerHTML = ''
  for (const q of dbHealth.slowQueries) {
    const tr = document.createElement('tr')

    const startedCell = document.createElement('td')
    startedCell.textContent = q.started
    const runTimeCell = document.createElement('td')
    runTimeCell.textContent = q.runTime.toFixed(3)
    const stateCell = document.createElement('td')
    stateCell.textContent = q.state

    const queryCell = document.createElement('td')
    queryCell.appendChild(makeCollapsible(q.query, truncateOneLine(q.query, 80)))

    const bindVarsCell = document.createElement('td')
    const bindVarsText = JSON.stringify(q.bindVars)
    bindVarsCell.appendChild(makeCollapsible(bindVarsText, truncateOneLine(bindVarsText, 60)))

    tr.appendChild(startedCell)
    tr.appendChild(runTimeCell)
    tr.appendChild(stateCell)
    tr.appendChild(queryCell)
    tr.appendChild(bindVarsCell)
    tbody.appendChild(tr)
  }
}

const loadButton = document.getElementById('load')

loadButton.addEventListener('click', async () => {
  const hours = document.getElementById('hours').value
  const stage = document.getElementById('stage').value
  const statusEl = document.getElementById('status')
  statusEl.classList.remove('error')
  statusEl.textContent = 'Querying CloudWatch Logs Insights and ArangoDB - this can take up to ~30s...'
  loadButton.disabled = true
  try {
    const response = await fetch('/internal/analytics/queries?hours=' + encodeURIComponent(hours) + '&stage=' + encodeURIComponent(stage))
    if (!response.ok) {
      statusEl.classList.add('error')
      statusEl.textContent = 'Request failed: ' + response.status
      return
    }
    const data = await response.json()
    renderTopPaths(data.topPaths)
    renderDbHealth(data.dbHealth)
    statusEl.textContent = 'Loaded ' + data.topPaths.length + ' path(s) for the last ' + data.hours + ' hour(s).'
  } catch (error) {
    statusEl.classList.add('error')
    statusEl.textContent = 'Request failed: ' + error
  } finally {
    loadButton.disabled = false
  }
})
</script>
</body>
</html>`

export const internalAnalyticsRouter = Router()

internalAnalyticsRouter.get('/', (_req, res) => {
  res.type('html').send(PANEL_HTML)
})

internalAnalyticsRouter.get('/queries', (req, res) => {
  handleQueriesRequest(req, res).catch((error) => {
    console.error('Failed to build analytics snapshot', error)
    res.status(500).json({ error: 'Failed to build analytics snapshot' })
  })
})
