import pytest
from jsonschema import Draft202012Validator, ValidationError

from schemas.registry import get_schema

REQUIRED_FIELDS = [
    '_key', 'name', 'source', 'source_url',
    'chr', 'pos', 'ref', 'alt', 'variation_type', 'spdi', 'hgvs', 'organism'
]


@pytest.fixture(scope='module')
def schema():
    return get_schema('nodes', 'variants', 'autogenerated_topld')


@pytest.fixture
def valid_doc():
    return {
        '_key': 'NC_000001.11:10000:T:A',
        'name': 'NC_000001.11:10000:T:A',
        'chr': 'chr1',
        'pos': 10000,
        'ref': 'T',
        'alt': 'A',
        'spdi': 'NC_000001.11:10000:T:A',
        'hgvs': 'NC_000001.11:g.10001T>A',
        'vrs_digest': 'ga4gh:VA.abc123',
        'organism': 'Homo sapiens',
        'variation_type': 'SNP',
        'source': 'Autogenerated from TopLD',
        'source_url': 'http://topld.genetics.unc.edu/'
    }


def test_db_collection_name(schema):
    assert schema['db_collection_name'] == 'variants'


def test_additional_properties_disallowed(schema):
    assert schema['additionalProperties'] is False


def test_required_fields(schema):
    assert set(schema['required']) == set(REQUIRED_FIELDS)


def test_valid_document_passes(schema, valid_doc):
    Draft202012Validator(schema).validate(valid_doc)


def test_valid_document_without_optional_fields_passes(schema, valid_doc):
    del valid_doc['vrs_digest']
    Draft202012Validator(schema).validate(valid_doc)


@pytest.mark.parametrize('field', REQUIRED_FIELDS)
def test_missing_required_field_fails(schema, valid_doc, field):
    del valid_doc[field]
    with pytest.raises(ValidationError):
        Draft202012Validator(schema).validate(valid_doc)


def test_wrong_source_fails(schema, valid_doc):
    valid_doc['source'] = 'TopLD'
    with pytest.raises(ValidationError):
        Draft202012Validator(schema).validate(valid_doc)


def test_wrong_source_url_fails(schema, valid_doc):
    valid_doc['source_url'] = 'https://example.com/'
    with pytest.raises(ValidationError):
        Draft202012Validator(schema).validate(valid_doc)


def test_unknown_field_rejected(schema, valid_doc):
    # regression check for the 'variantion_type' typo bug in the generator script
    valid_doc['variantion_type'] = 'SNP'
    with pytest.raises(ValidationError):
        Draft202012Validator(schema).validate(valid_doc)


def test_wrong_type_fails(schema, valid_doc):
    valid_doc['pos'] = 'not-a-number'
    with pytest.raises(ValidationError):
        Draft202012Validator(schema).validate(valid_doc)
