genes_genes = {
    '/genes/genes': [{
        'params': {
            'gene_id': 'ENSG00000170558',
            'source': 'CoXPresdb',
            'logit_score': 'gt:0.1',
        },
        'response': [{
            'gene': {
                '_key': 'ENSG00000121410',
                'alias': ['alpha-1-B glycoprotein',
                     'GAB',
                          'HEL-S-163pA',
                          'A1BG',
                          'HYST2477',
                          'alpha-1B-glycoprotein',
                          'ABG',
                          'A1B',
                          'epididymis secretory sperm binding protein Li 163pA'],
                'chr': 'chr19',
                'end:long': 58353492,
                'entrez': '1',
                'gene_id': 'ENSG00000121410.12',
                'gene_type': 'protein_coding',
                'hgnc': 'HGNC:5',
                'name': 'A1BG',
                'source': 'GENCODE',
                'source_url': 'https://www.gencodegenes.org/human/',
                'start:long': 58345177,
                'version': 'v43'},
            'logit_score': 0.13,
            'source': 'CoXPresdb',
            'source_url': 'https://coxpresdb.jp/'},
            {
            'gene': {
                '_key': 'ENSG00000121410',
                'alias': ['alpha-1-B glycoprotein',
                          'GAB',
                          'HEL-S-163pA',
                          'A1BG',
                          'HYST2477',
                          'alpha-1B-glycoprotein',
                          'ABG',
                          'A1B',
                          'epididymis secretory sperm binding protein Li 163pA'],
                'chr': 'chr19',
                'end:long': 58353492,
                'entrez': '1',
                'gene_id': 'ENSG00000121410.12',
                'gene_type': 'protein_coding',
                'hgnc': 'HGNC:5',
                'name': 'A1BG',
                'source': 'GENCODE',
                'source_url': 'https://www.gencodegenes.org/human/',
                'start:long': 58345177,
                'version': 'v43'},
                'logit_score': 0.13,
                'source': 'CoXPresdb',
                'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000077616',
                      'alias': ['GCP3',
                                'N-acetylated-alpha-linked acidic dipeptidase 2',
                                'NAALADase II',
                                'N-acetylated alpha-linked acidic dipeptidase 2',
                                'NAALADASE2',
                                'glutamate carboxypeptidase III',
                                'GCPIII',
                                'NAALAD2',
                                'N-acetylated alpha-linked acidic dipeptidase II',
                                'GPCIII'],
                      'chr': 'chr11',
                      'end:long': 90192894,
                      'entrez': '10003',
                      'gene_id': 'ENSG00000077616.11',
                      'gene_type': 'protein_coding',
                      'hgnc': 'HGNC:14526',
                      'name': 'NAALAD2',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 90131514,
                      'version': 'v43'},
             'logit_score': 1.01,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000233369',
                      'alias': ['GTF2I',
                                'GTF2IP4',
                                'general transcription factor IIi pseudogene 4',
                                'general transcription factor II, i, pseudogene'],
                      'chr': 'chr7',
                      'end:long': 73207283,
                      'entrez': '100093631',
                      'gene_id': 'ENSG00000233369.7',
                      'gene_type': 'transcribed_processed_pseudogene',
                      'hgnc': 'HGNC:51716',
                      'name': 'GTF2IP4',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 73154937,
                      'version': 'v43'},
             'logit_score': 1.34,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000213523',
                      'alias': ['SRAP',
                                'STRAA1',
                                'SRA1',
                                'pp7684',
                                'SRA',
                                'steroid receptor RNA activator protein',
                                'steroid receptor RNA activator 1 (complexes with NCOA1)',
                                'steroid receptor RNA activator 1',
                                'steroid receptor coactivator'],
                      'chr': 'chr5',
                      'end:long': 140557677,
                      'entrez': '10011',
                      'gene_id': 'ENSG00000213523.12',
                      'gene_type': 'protein_coding',
                      'hgnc': 'HGNC:11281',
                      'name': 'SRA1',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 140537339,
                      'version': 'v43'},
             'logit_score': 0.43,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000205269',
                      'alias': ['TMEM170B', 'transmembrane protein 170B'],
                      'chr': 'chr6',
                      'end:long': 11583524,
                      'entrez': '100113407',
                      'gene_id': 'ENSG00000205269.6',
                      'gene_type': 'protein_coding',
                      'hgnc': 'HGNC:34244',
                      'name': 'TMEM170B',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 11537748,
                      'version': 'v43'},
             'logit_score': 0.26,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000291071',
                      'alias': ['FAM86JP',
                                'family with sequence similarity 86 member J, pseudogene'],
                      'chr': 'chr3',
                      'end:long': 125930056,
                      'entrez': '100125556',
                      'gene_id': 'ENSG00000291071.1',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:44097',
                      'name': 'FAM86JP',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 125916608,
                      'version': 'v43'},
             'logit_score': 0.19,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000270607',
                      'alias': ['LEISA',
                                'NAV2-AS6',
                                'LEISA1',
                                'lncRNA enhancing IL-6/STAT3 signaling activation 1',
                                'lncRNA enhancing IL-6/STAT3 signaling activation',
                                'NAV2 antisense RNA 6'],
                      'chr': 'chr11',
                      'end:long': 19712619,
                      'entrez': '100126784',
                      'gene_id': 'ENSG00000270607.1',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:55264',
                      'name': 'NAV2-AS6',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 19710933,
                      'version': 'v43'},
             'logit_score': 0.44,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000253250',
                      'alias': ['chromosome 8 open reading frame 88',
                                'C8orf88',
                                'uncharacterized protein C8orf88'],
                      'chr': 'chr8',
                      'end:long': 90985238,
                      'entrez': '100127983',
                      'gene_id': 'ENSG00000253250.3',
                      'gene_type': 'protein_coding',
                      'hgnc': 'HGNC:44672',
                      'name': 'C8orf88',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 90958470,
                      'version': 'v43'},
             'logit_score': 1.57,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000166770',
                      'alias': ['Mortal Obligate RNA Transcript',
                                'ZNF667-AS1',
                                'MORT',
                                'ZNF667 antisense RNA 1 (head to head)'],
                      'chr': 'chr19',
                      'end:long': 56504362,
                      'entrez': '100128252',
                      'gene_id': 'ENSG00000166770.12',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:44321',
                      'name': 'ZNF667-AS1',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 56477249,
                      'version': 'v43'},
             'logit_score': 0.26,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000176593',
                      'alias': ['ZNF606-AS1', 'ZNF606 antisense RNA 1'],
                      'chr': 'chr19',
                      'end:long': 58011232,
                      'entrez': '100128398',
                      'gene_id': 'ENSG00000176593.8',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:44322',
                      'name': 'ENSG00000176593',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 58002060,
                      'version': 'v43'},
             'logit_score': 0.84,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000183397',
                      'alias': ['tektin bundle-interacting protein 1',
                                'uncharacterized protein C19orf71',
                                'tektin bundle interacting protein 1',
                                'TEKTIP1',
                                'C19orf71'],
                      'chr': 'chr19',
                      'end:long': 3544030,
                      'entrez': '100128569',
                      'gene_id': 'ENSG00000183397.6',
                      'gene_type': 'protein_coding',
                      'hgnc': 'HGNC:34496',
                      'name': 'TEKTIP1',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 3539170,
                      'version': 'v43'},
             'logit_score': 0.49,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000266010',
                      'alias': ['GATA6 antisense RNA 1 (head to head)',
                                'locus 5689',
                                'locus5689',
                                'BM742401',
                                'GATA6-AS1'],
                      'chr': 'chr18',
                      'end:long': 22169878,
                      'entrez': '100128893',
                      'gene_id': 'ENSG00000266010.4',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:48840',
                      'name': 'GATA6-AS1',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 22164885,
                      'version': 'v43'},
             'logit_score': 1.84,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000179627',
                      'alias': ['zinc finger and BTB domain containing 42',
                                'zinc finger and BTB domain-containing protein 42',
                                'ZNF925',
                                'LCCS6',
                                'ZBTB42'],
                      'chr': 'chr14',
                      'end:long': 104804712,
                      'entrez': '100128927',
                      'gene_id': 'ENSG00000179627.10',
                      'gene_type': 'protein_coding',
                      'hgnc': 'HGNC:32550',
                      'name': 'ZBTB42',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 104800595,
                      'version': 'v43'},
             'logit_score': 0.12,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000235016',
                      'alias': ['SEMA3F antisense RNA 1', 'RBM5-AS1', 'SEMA3F-AS1'],
                      'chr': 'chr3',
                      'end:long': 50156085,
                      'entrez': '100129060',
                      'gene_id': 'ENSG00000235016.1',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:40518',
                      'name': 'SEMA3F-AS1',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 50116021,
                      'version': 'v43'},
             'logit_score': 0.13,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000256537',
                      'alias': ['chromosome X open reading frame 69-like',
                                'small integral membrane protein 10 like 1',
                                'Small integral membrane protein 10-like protein 1',
                                'SMIM10L1',
                                'small integral membrane protein 10-like protein 1'],
                      'chr': 'chr12',
                      'end:long': 11176016,
                      'entrez': '100129361',
                      'gene_id': 'ENSG00000256537.5',
                      'gene_type': 'protein_coding',
                      'hgnc': 'HGNC:49847',
                      'name': 'SMIM10L1',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 11171193,
                      'version': 'v43'},
             'logit_score': 0.22,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000233251',
                      'alias': ['LOC100129434'],
                      'chr': 'chr2',
                      'end:long': 56185870,
                      'entrez': '100129434',
                      'gene_id': 'ENSG00000233251.8',
                      'gene_type': 'lncRNA',
                      'name': 'ENSG00000233251',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 56173533,
                      'version': 'v43'},
             'logit_score': 0.29,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000234432',
                      'alias': ['LINC02983',
                                'long intergenic non-protein coding RNA 2983'],
                      'chr': 'chr7',
                      'end:long': 5428927,
                      'entrez': '100129484',
                      'gene_id': 'ENSG00000234432.4',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:56060',
                      'name': 'LINC02983',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 5426276,
                      'version': 'v43'},
             'logit_score': 1.25,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000262454',
                      'alias': ['linc noncoding oxygen-sensitive regulator of sterol '
                                'homeostasis',
                                'MIR193BHG',
                                'lincNORS',
                                'MIR193b-365a host gene',
                                'noncoding oxygen-sensitive regulator of sterol '
                                'homeostasis',
                                'HypERlnc',
                                'MIR193B host',
                                'hypoxia-induced endoplasmic reticulum stress regulating '
                                'long noncoding RNA'],
                      'chr': 'chr16',
                      'end:long': 14331067,
                      'entrez': '100129781',
                      'gene_id': 'ENSG00000262454.4',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:51945',
                      'name': 'MIR193BHG',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 14301388,
                      'version': 'v43'},
             'logit_score': 0.49,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000237440',
                      'alias': ['ZNF737',
                                'zinc finger protein 737',
                                'ZNF102',
                                'zinc finger protein 102 (Y3)'],
                      'chr': 'chr19',
                      'end:long': 20565809,
                      'entrez': '100129842',
                      'gene_id': 'ENSG00000237440.9',
                      'gene_type': 'protein_coding',
                      'hgnc': 'HGNC:32468',
                      'name': 'ZNF737',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 20535824,
                      'version': 'v43'},
             'logit_score': 0.68,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000224043',
                      'alias': ['CCNT2 antisense RNA 1', 'CCNT2-AS1'],
                      'chr': 'chr2',
                      'end:long': 134918712,
                      'entrez': '100129961',
                      'gene_id': 'ENSG00000224043.9',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:40130',
                      'name': 'CCNT2-AS1',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 134735463,
                      'version': 'v43'},
             'logit_score': 0.69,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000094631',
                      'alias': ['HD6',
                                'histone deacetylase 6',
                                'protein phosphatase 1, regulatory subunit 90',
                                'PPP1R90',
                                'HDAC6',
                                'JM21',
                                'CPBHM',
                                'tubulin-lysine deacetylase HDAC6'],
                      'chr': 'chrX',
                      'end:long': 48824982,
                      'entrez': '10013',
                      'gene_id': 'ENSG00000094631.22',
                      'gene_type': 'protein_coding',
                      'hgnc': 'HGNC:14064',
                      'name': 'HDAC6',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 48801376,
                      'version': 'v43'},
             'logit_score': 0.12,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000256802',
                      'alias': ['LCIIAR',
                                'lung cancer immune cell infiltration associated lncRNA'],
                      'chr': 'chr15',
                      'end:long': 29680957,
                      'entrez': '100130111',
                      'gene_id': 'ENSG00000256802.3',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:56346',
                      'name': 'ENSG00000256802',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 29674931,
                      'version': 'v43'},
             'logit_score': 0.77,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000223764',
                      'alias': ['LINC02593',
                                'long intergenic non-protein coding RNA 2593'],
                      'chr': 'chr1',
                      'end:long': 921016,
                      'entrez': '100130417',
                      'gene_id': 'ENSG00000223764.2',
                      'gene_type': 'lncRNA',
                      'hgnc': 'HGNC:53933',
                      'name': 'LINC02593',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 916864,
                      'version': 'v43'},
             'logit_score': 0.67,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'},
            {'gene': {'_key': 'ENSG00000213963',
                      'alias': ['LOC100130691'],
                      'chr': 'chr2',
                      'end:long': 177392699,
                      'entrez': '100130691',
                      'gene_id': 'ENSG00000213963.7',
                      'gene_type': 'lncRNA',
                      'name': 'ENSG00000213963',
                      'source': 'GENCODE',
                      'source_url': 'https://www.gencodegenes.org/human/',
                      'start:long': 177271124,
                      'version': 'v43'},
             'logit_score': 0.4,
             'source': 'CoXPresdb',
             'source_url': 'https://coxpresdb.jp/'
             }]
    }]
}
